/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.crm.application;

import com.crm.Database.MySql;
import com.crm.Entity.Role;
import com.crm.Entity.User;
import com.crm.Module.Dao.Module;
import com.crm.Module.RoleModule;
import com.crm.Module.UserModule;
import com.crm.Tools.Constants;

import javax.swing.*;
import java.util.List;

/**
 *
 * @author Meghdad BSSI
 */
public class AppCRM extends JFrame {

    /**
     * Creates new form AppCRM
     */
    public AppCRM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        MySql.init(Constants.DATABASE_NAME, Constants.DATABASE_USER, Constants.DATABASE_PASS);
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabUser = new javax.swing.JPanel();
        panelScrollUser = new javax.swing.JScrollPane();
        tableUser = new javax.swing.JTable();
        tabAddUser = new javax.swing.JPanel();
        JtxtFirstname = new javax.swing.JTextField();
        JtxtLastname = new javax.swing.JTextField();
        JtxtMail = new javax.swing.JTextField();
        JtxtPassword = new javax.swing.JTextField();
        JtxtUsername = new javax.swing.JTextField();
        JtxtPhone = new javax.swing.JTextField();
        JtxtAddress = new javax.swing.JTextField();
        JtxtCity = new javax.swing.JTextField();
        jCmbRole = new javax.swing.JComboBox<String>();

        /* add role to combo box */
        try {

            Module<Role> d = new RoleModule();
            List<Role> data = d.findAll(new Role());
            for (Role p : data) {
                jCmbRole.addItem(p.getName());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        prenomLabel = new javax.swing.JLabel();
        nomLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        telLabel = new javax.swing.JLabel();
        adressLabel = new javax.swing.JLabel();
        villeLabel = new javax.swing.JLabel();
        roleLabel = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        tabRole = new javax.swing.JPanel();
        panelScrollRole = new javax.swing.JScrollPane();
        tableRole = new javax.swing.JTable();
        tabAddRole = new javax.swing.JPanel();
        tabSendMessage = new javax.swing.JPanel();
        panelSendMessage = new javax.swing.JScrollPane();
        messageTextArea = new javax.swing.JTextArea();
        buttonSendMessage = new javax.swing.JButton();
        messageLabel = new javax.swing.JLabel();
        tabModuleList = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Pénélope F");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(102, 102, 102));

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tabUser.setName(""); // NOI18N

        /* add role to combo box */
        try {

            Module<User> d = new UserModule();
            List<User> data = d.findAll(new User());
            Object[][] myObj = new Object[data.size()][5];
            for (User p : data) {
                myObj[p.getId() - 1][0] = p.getFirstname();
                myObj[p.getId() - 1][1] = p.getLastname();
                myObj[p.getId() - 1][2] = p.getEmail();
                myObj[p.getId() - 1][3] = p.getAddress();
                myObj[p.getId() - 1][4] = p.getRoles();
            }

            tableUser.setModel(new javax.swing.table.DefaultTableModel(
                myObj,
                new String [] {
                    "Prénom", "Nom", "Email", "Username", "Role"
                }
            ) {
                Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }
            });
            panelScrollUser.setViewportView(tableUser);
        } catch (Exception e) {
            e.printStackTrace();
        }

        javax.swing.GroupLayout tabUserLayout = new javax.swing.GroupLayout(tabUser);
        tabUser.setLayout(tabUserLayout);
        tabUserLayout.setHorizontalGroup(
            tabUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelScrollUser, javax.swing.GroupLayout.DEFAULT_SIZE, 1046, Short.MAX_VALUE)
        );
        tabUserLayout.setVerticalGroup(
            tabUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabUserLayout.createSequentialGroup()
                .addGap(0, 127, Short.MAX_VALUE)
                .addComponent(panelScrollUser, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Utilisateurs", tabUser);

        prenomLabel.setText("Prénoms");
        nomLabel.setText("Nom");

        emailLabel.setText("Email");

        passLabel.setText("Mot de passe");

        usernameLabel.setText("Username");

        telLabel.setText("Téléphone");

        adressLabel.setText("Adresse");

        villeLabel.setText("Ville");

        roleLabel.setText("Role");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout tabAddUserLayout = new javax.swing.GroupLayout(tabAddUser);
        tabAddUser.setLayout(tabAddUserLayout);
        tabAddUserLayout.setHorizontalGroup(
            tabAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAddUserLayout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addGroup(tabAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prenomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel)
                    .addComponent(passLabel)
                    .addComponent(usernameLabel)
                    .addComponent(telLabel)
                    .addComponent(adressLabel)
                    .addComponent(villeLabel)
                    .addComponent(nomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JtxtLastname)
                    .addComponent(JtxtMail)
                    .addComponent(JtxtPassword)
                    .addComponent(JtxtUsername)
                    .addComponent(JtxtPhone)
                    .addComponent(JtxtAddress)
                    .addComponent(JtxtCity)
                    .addComponent(jCmbRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tabAddUserLayout.createSequentialGroup()
                        .addComponent(JtxtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(319, 319, 319)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );
        tabAddUserLayout.setVerticalGroup(
            tabAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAddUserLayout.createSequentialGroup()
                .addGroup(tabAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tabAddUserLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(tabAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JtxtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prenomLabel))
                        .addGap(18, 18, 18)
                        .addGroup(tabAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabAddUserLayout.createSequentialGroup()
                                .addComponent(JtxtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JtxtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JtxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JtxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JtxtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JtxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tabAddUserLayout.createSequentialGroup()
                                .addGroup(tabAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(tabAddUserLayout.createSequentialGroup()
                                        .addGroup(tabAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(tabAddUserLayout.createSequentialGroup()
                                                .addComponent(nomLabel)
                                                .addGap(18, 18, 18)
                                                .addComponent(emailLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(passLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(usernameLabel)
                                                .addGap(44, 44, 44))
                                            .addComponent(telLabel))
                                        .addGap(38, 38, 38))
                                    .addGroup(tabAddUserLayout.createSequentialGroup()
                                        .addGap(201, 201, 201)
                                        .addComponent(adressLabel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(villeLabel))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tabAddUserLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JtxtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tabAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roleLabel))
                .addContainerGap(234, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ajouter Utilisateur", null, tabAddUser, "");

        tableRole.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Prénom", "Nom", "Email", "Username", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        panelScrollRole.setViewportView(tableRole);

        javax.swing.GroupLayout tabRoleLayout = new javax.swing.GroupLayout(tabRole);
        tabRole.setLayout(tabRoleLayout);
        tabRoleLayout.setHorizontalGroup(
            tabRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelScrollRole, javax.swing.GroupLayout.DEFAULT_SIZE, 1046, Short.MAX_VALUE)
        );
        tabRoleLayout.setVerticalGroup(
            tabRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabRoleLayout.createSequentialGroup()
                .addGap(0, 127, Short.MAX_VALUE)
                .addComponent(panelScrollRole, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Les Roles", tabRole);

        javax.swing.GroupLayout tabAddRoleLayout = new javax.swing.GroupLayout(tabAddRole);
        tabAddRole.setLayout(tabAddRoleLayout);
        tabAddRoleLayout.setHorizontalGroup(
            tabAddRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1046, Short.MAX_VALUE)
        );
        tabAddRoleLayout.setVerticalGroup(
            tabAddRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 721, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Ajouter Role", tabAddRole);

        tabSendMessage.setVerifyInputWhenFocusTarget(false);

        messageTextArea.setColumns(20);
        messageTextArea.setRows(5);
        panelSendMessage.setViewportView(messageTextArea);

        buttonSendMessage.setText("Envoyer");

        messageLabel.setText("Votre Message");

        javax.swing.GroupLayout tabSendMessageLayout = new javax.swing.GroupLayout(tabSendMessage);
        tabSendMessage.setLayout(tabSendMessageLayout);
        tabSendMessageLayout.setHorizontalGroup(
            tabSendMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabSendMessageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabSendMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSendMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 1034, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabSendMessageLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonSendMessage))
                    .addGroup(tabSendMessageLayout.createSequentialGroup()
                        .addComponent(messageLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tabSendMessageLayout.setVerticalGroup(
            tabSendMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabSendMessageLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(messageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSendMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonSendMessage)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Message", tabSendMessage);

        javax.swing.GroupLayout tabModuleListLayout = new javax.swing.GroupLayout(tabModuleList);
        tabModuleList.setLayout(tabModuleListLayout);
        tabModuleListLayout.setHorizontalGroup(
            tabModuleListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1046, Short.MAX_VALUE)
        );
        tabModuleListLayout.setVerticalGroup(
            tabModuleListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 721, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Les Module", tabModuleList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1067, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        setSize(new java.awt.Dimension(1073, 789));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main_(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppCRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppCRM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JtxtAddress;
    private javax.swing.JTextField JtxtCity;
    private javax.swing.JTextField JtxtFirstname;
    private javax.swing.JTextField JtxtLastname;
    private javax.swing.JTextField JtxtMail;
    private javax.swing.JTextField JtxtPassword;
    private javax.swing.JTextField JtxtPhone;
    private javax.swing.JTextField JtxtUsername;
    private javax.swing.JLabel adressLabel;
    private javax.swing.JButton buttonSendMessage;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JComboBox<String> jCmbRole;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JTextArea messageTextArea;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JScrollPane panelScrollRole;
    private javax.swing.JScrollPane panelScrollUser;
    private javax.swing.JScrollPane panelSendMessage;
    private javax.swing.JLabel passLabel;
    private javax.swing.JLabel prenomLabel;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JPanel tabAddRole;
    private javax.swing.JPanel tabAddUser;
    private javax.swing.JPanel tabModuleList;
    private javax.swing.JPanel tabRole;
    private javax.swing.JPanel tabSendMessage;
    private javax.swing.JPanel tabUser;
    private javax.swing.JTable tableRole;
    private javax.swing.JTable tableUser;
    private javax.swing.JLabel telLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel villeLabel;
    // End of variables declaration//GEN-END:variables
}
