/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.crm.application;

import javax.swing.*;

/**
 *
 * @author Meghdad BSSI
 */
public class AppCRM extends JFrame {

    /**
     * Creates new form AppCRM
     */
    public AppCRM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabUser = new javax.swing.JPanel();
        panelScrollUser = new javax.swing.JScrollPane();
        tableUser = new javax.swing.JTable();
        tabAddUser = new javax.swing.JPanel();
        JtxtFirstname = new javax.swing.JTextField();
        JtxtLastname = new javax.swing.JTextField();
        JtxtMail = new javax.swing.JTextField();
        JtxtPassword = new javax.swing.JTextField();
        JtxtUsername = new javax.swing.JTextField();
        JtxtPhone = new javax.swing.JTextField();
        JtxtAddress = new javax.swing.JTextField();
        JtxtCity = new javax.swing.JTextField();
        jCmbRole = new javax.swing.JComboBox<String>();
        prenomLabel = new javax.swing.JLabel();
        nomLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        telLabel = new javax.swing.JLabel();
        adressLabel = new javax.swing.JLabel();
        villeLabel = new javax.swing.JLabel();
        roleLabel = new javax.swing.JLabel();
        tabRole = new javax.swing.JPanel();
        panelScrollRole = new javax.swing.JScrollPane();
        tableRole = new javax.swing.JTable();
        tabAddRole = new javax.swing.JPanel();
        tabSendMessage = new javax.swing.JPanel();
        panelSendMessage = new javax.swing.JScrollPane();
        messageTextArea = new javax.swing.JTextArea();
        buttonSendMessage = new javax.swing.JButton();
        messageLabel = new javax.swing.JLabel();
        tabModuleList = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Pénélope F");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(102, 102, 102));

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tabUser.setName(""); // NOI18N

        tableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Prénom", "Nom", "Email", "Username", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        panelScrollUser.setViewportView(tableUser);

        javax.swing.GroupLayout tabUserLayout = new javax.swing.GroupLayout(tabUser);
        tabUser.setLayout(tabUserLayout);
        tabUserLayout.setHorizontalGroup(
            tabUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelScrollUser, javax.swing.GroupLayout.DEFAULT_SIZE, 1126, Short.MAX_VALUE)
        );
        tabUserLayout.setVerticalGroup(
            tabUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabUserLayout.createSequentialGroup()
                .addGap(0, 115, Short.MAX_VALUE)
                .addComponent(panelScrollUser, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Utilisateurs", tabUser);

        jCmbRole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        prenomLabel.setText("Prénoms");

        nomLabel.setText("Nom");

        emailLabel.setText("Mail");

        passLabel.setText("mot de passe");

        usernameLabel.setText("Identifiant");

        telLabel.setText("Tel");

        adressLabel.setText("Adresse");

        villeLabel.setText("Ville");

        roleLabel.setText("Role");

        javax.swing.GroupLayout tabAddUserLayout = new javax.swing.GroupLayout(tabAddUser);
        tabAddUser.setLayout(tabAddUserLayout);
        tabAddUserLayout.setHorizontalGroup(
            tabAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAddUserLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(tabAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JtxtLastname)
                    .addComponent(JtxtFirstname)
                    .addComponent(JtxtMail)
                    .addComponent(JtxtPassword)
                    .addComponent(JtxtUsername)
                    .addComponent(JtxtPhone)
                    .addComponent(JtxtAddress)
                    .addComponent(JtxtCity)
                    .addComponent(jCmbRole, 0, 389, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(tabAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prenomLabel)
                    .addComponent(nomLabel)
                    .addComponent(emailLabel)
                    .addComponent(passLabel)
                    .addComponent(usernameLabel)
                    .addComponent(telLabel)
                    .addComponent(adressLabel)
                    .addComponent(villeLabel)
                    .addComponent(roleLabel))
                .addGap(478, 478, 478))
        );
        tabAddUserLayout.setVerticalGroup(
            tabAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAddUserLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(tabAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tabAddUserLayout.createSequentialGroup()
                        .addGroup(tabAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(tabAddUserLayout.createSequentialGroup()
                                .addGroup(tabAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JtxtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(prenomLabel))
                                .addGap(18, 18, 18)
                                .addGroup(tabAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JtxtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nomLabel))
                                .addGap(18, 18, 18)
                                .addGroup(tabAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JtxtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(tabAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JtxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tabAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JtxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usernameLabel))
                                .addGap(18, 18, 18)
                                .addComponent(JtxtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(telLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JtxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(adressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JtxtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(villeLabel))
                .addGap(18, 18, 18)
                .addGroup(tabAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roleLabel))
                .addContainerGap(264, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ajouter Utilisateur", null, tabAddUser, "");

        tableRole.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Prénom", "Nom", "Email", "Username", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        panelScrollRole.setViewportView(tableRole);

        javax.swing.GroupLayout tabRoleLayout = new javax.swing.GroupLayout(tabRole);
        tabRole.setLayout(tabRoleLayout);
        tabRoleLayout.setHorizontalGroup(
            tabRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelScrollRole, javax.swing.GroupLayout.DEFAULT_SIZE, 1126, Short.MAX_VALUE)
        );
        tabRoleLayout.setVerticalGroup(
            tabRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabRoleLayout.createSequentialGroup()
                .addGap(0, 115, Short.MAX_VALUE)
                .addComponent(panelScrollRole, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Les Roles", tabRole);

        javax.swing.GroupLayout tabAddRoleLayout = new javax.swing.GroupLayout(tabAddRole);
        tabAddRole.setLayout(tabAddRoleLayout);
        tabAddRoleLayout.setHorizontalGroup(
            tabAddRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1126, Short.MAX_VALUE)
        );
        tabAddRoleLayout.setVerticalGroup(
            tabAddRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Ajouter Role", tabAddRole);

        tabSendMessage.setVerifyInputWhenFocusTarget(false);

        messageTextArea.setColumns(20);
        messageTextArea.setRows(5);
        panelSendMessage.setViewportView(messageTextArea);

        buttonSendMessage.setText("Envoyer");

        messageLabel.setText("Votre Message");

        javax.swing.GroupLayout tabSendMessageLayout = new javax.swing.GroupLayout(tabSendMessage);
        tabSendMessage.setLayout(tabSendMessageLayout);
        tabSendMessageLayout.setHorizontalGroup(
            tabSendMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabSendMessageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabSendMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSendMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 1114, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabSendMessageLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonSendMessage))
                    .addGroup(tabSendMessageLayout.createSequentialGroup()
                        .addComponent(messageLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tabSendMessageLayout.setVerticalGroup(
            tabSendMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabSendMessageLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(messageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSendMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonSendMessage)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Message", tabSendMessage);

        javax.swing.GroupLayout tabModuleListLayout = new javax.swing.GroupLayout(tabModuleList);
        tabModuleList.setLayout(tabModuleListLayout);
        tabModuleListLayout.setHorizontalGroup(
            tabModuleListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1126, Short.MAX_VALUE)
        );
        tabModuleListLayout.setVerticalGroup(
            tabModuleListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Les Module", tabModuleList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(916, 789));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main_(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppCRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppCRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppCRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppCRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppCRM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JtxtAddress;
    private javax.swing.JTextField JtxtCity;
    private javax.swing.JTextField JtxtFirstname;
    private javax.swing.JTextField JtxtLastname;
    private javax.swing.JTextField JtxtMail;
    private javax.swing.JTextField JtxtPassword;
    private javax.swing.JTextField JtxtPhone;
    private javax.swing.JTextField JtxtUsername;
    private javax.swing.JLabel adressLabel;
    private javax.swing.JButton buttonSendMessage;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JComboBox<String> jCmbRole;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JTextArea messageTextArea;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JScrollPane panelScrollRole;
    private javax.swing.JScrollPane panelScrollUser;
    private javax.swing.JScrollPane panelSendMessage;
    private javax.swing.JLabel passLabel;
    private javax.swing.JLabel prenomLabel;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JPanel tabAddRole;
    private javax.swing.JPanel tabAddUser;
    private javax.swing.JPanel tabModuleList;
    private javax.swing.JPanel tabRole;
    private javax.swing.JPanel tabSendMessage;
    private javax.swing.JPanel tabUser;
    private javax.swing.JTable tableRole;
    private javax.swing.JTable tableUser;
    private javax.swing.JLabel telLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel villeLabel;
    // End of variables declaration//GEN-END:variables
}
